docstring = raw"""
Plots the solution time benchmarks generated by running benchmark/benchmark.jl.

# Usage

## From shell
```bash
$ julia plot_benchmark.jl <benchmark_file.json>  <convergence_file.jld2>
```

## From Julia REPL
```julia
julia> ARGS = [<benchmark_file.json>  <convergence_file.jld2>]
julia> include("plot_benchmark.jl")
```
"""
using BenchmarkTools
using GLMakie
using JLD2
using Statistics

using BoundaryIntegralEquations, BoundaryIntegralEquations.DevTools

include("plot_utils.jl")

###########
# Read data
###########
try
    global benchmark_result = BenchmarkTools.load(ARGS[1])[1] # [1] because json stores a vector of results
    global res = load_object(ARGS[2])
catch e
    @info docstring
    rethrow(e)
end

mx = sqrt(size(res.x, 2))
###########
# Make figure
###########
# ncols = 5
# nrows = 2
w=1200
fig = Figure(
    title="$(mx) x $(mx) evaluation grid",
    size=(w, w*9÷16)
)
nticks = 5
cm = Makie.to_colormap(:tab10)
ax_time = Axis(
    fig[1, 1],
    xlabel="N",
    ylabel="Time (ms)",
    xscale=log10,
    yscale=log10,
    xticks=LinearTicks(nticks),
    yticks=LinearTicks(nticks),
    ytickformat=values -> [string(v/1e+6) for v in values],
    palette=(; color=cm,)
)

# ax_scaling = Axis(
#     fig[1, end+1],
#     xlabel="N",
#     ylabel="Relative Overhead vs. N₁",
#     xscale=log10,
#     yscale=log10,
#     xticks=LinearTicks(nticks),
#     yticks=LinearTicks(nticks),
#     ytickformat=values -> [isinteger(v) ? "$(Int(v))x" : "$(v)x" for v in values],
# )

ax_slowdown = Axis(
    fig[1, end+1],
    xlabel="N",
    ylabel="Slowdown",
    xscale=log10,
    # yscale=log10,
    xticks=LinearTicks(nticks),
    yticks=LinearTicks(nticks),
    # xtickformat=values -> [isinteger(v) ? "$(Int(v))x" : "$(v)x" for v in values],
    ytickformat=values -> [isinteger(v) ? "$(Int(v))x" : "$(v)x" for v in values],
    palette=(; color=cm,)
)

###########
# Filter data
###########
filter!(
    res,
    (k) -> begin
        if !(order(k.correction) in [32,])
            return false
        end
        # if !(cutoff(k.evalmethod) in [0.0, 0.25])
        #     return false
        # end
        if !(k.solution_t <: BVPSolution)
            return false
        end
        if !(k.bdrycond_t <: Dirichlet)
            return false
        end
        if !(k.approach_t <: Indirect)

            return false
        end
        return true
    end
)

res |> display

# decide what metric to use from benchmarking (times, gctimes, etc...)
metric = :times
# decide what estimator to use for summarizing the times (median, mean, etc...)
estimator = median

# the reference run is the fastest solver, used to compute slowdown of more accurate
# solvers
reference_run = minimum(keys(res.solutions))
# fetch the reference trials associated to each n value
reference_times = [
    begin
        # index of the benchmark trial
        id = get_string(
            bvp(soln), res.x, reference_run.correction, reference_run.approach_t(),
            reference_run.evalmethod
        )
        # the trial at this n value
        trial = benchmark_result[id]
        # e.g. the mean time at each n value
        estimator(getproperty(trial, metric))
    end
    for soln in solutions(res.solutions[reference_run])
]

@show reference_run, reference_times


# iterate over solutions and add elements to the plot
for (i, key) in enumerate(res.solutions |> keys |> collect |> sort)

    group = res.solutions[key]

    ns = numpoints.(solutions(group))


    # get all the benchmarking trials related to each n value
    # WARN: code duplicated for extracting trials
    times = [
        begin
            # index of the benchmark trial
            s = get_string(bvp(soln), res.x, key.correction, key.approach_t(), key.evalmethod)
            # the trial at this n value
            trial = benchmark_result[s]
            getproperty(trial, metric)
        end
        for soln in solutions(group)
    ]

    mids = estimator.(times)
    coarsest_times = mids[1]
    los = quantile.(times, 0.25)
    his = quantile.(times, 0.75)

    @show key
    kwargs = scatterlines_common_kwargs(key, res)

    for (ax, ref_val) in zip(
        [
            ax_time,
            # ax_scaling,
            ax_slowdown
        ],
        [
            1.,
            # coarsest_times,
            reference_times
        ]
    )




        scatterlines!(ax, ns, mids ./ ref_val;
            marker=MARKER_LABELS[i],
            markersize=i,
            cycle=[
                [:color, :strokecolor, :linecolor]=>:color,
            ],
            label="$(cutoff(key.evalmethod))",
            kwargs...)

        rangebars!(
            ax, ns,
            los ./ ref_val,
            his ./ ref_val,
            whiskerwidth=20,
            # colormap=kwargs.colormap,
            # colorrange=kwargs.colorrange,
            # color=fill(i, length(ns)),
            # alpha=0.3,
        )
    end
end


lines!(
    ax_time, res.n_vals, 5 * reference_times[1] .* (res.n_vals ./ res.n_vals[1]),
    label="O(N)",
    color=:grey,
    linewidth=3,
    alpha=0.5,
    linestyle=:dot
)

l = axislegend(ax_time, position=:rb)
Label(fig[0, :],
    "Background Grid $(mx) x $(mx)",
    fontsize=20,
    font=:bold)

# c1, c2, c3 = scatterlines_common_colorbars!(fig, res)
# legend = scatterlines_common_legend!(fig, res)
# # legend.halign=:left
# fig[1, end+1][1, 1] = c1
# fig[1, end][1, 2] = c2
# fig[1, end][1, 3] = c3
# fig[0, 1:end] = legend

plotfile =
    joinpath("figures", basename(@__FILE__) * begin
        if nameof(Makie.current_backend()) === :CairoMakie
            ".pdf"
        else
            ".png"
        end
    end
    )
save(plotfile, fig)
@info "saved `fig` to $(plotfile)"
fig

